// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvdgjizbdhyaqpkaqtko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2ZGdqaXpiZGh5YXFwa2FxdGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjkxMzMsImV4cCI6MjA2Nzc0NTEzM30.g9mNHFYxE-GS-FG-UtytoygXaGRsk31C01tAyTYXyK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});